// Generated by CoffeeScript 1.6.3
(function() {
  var cli, commander, config, deploy, _, _p;

  commander = require('commander');

  _ = require('underscore');

  _p = require('../package');

  deploy = require('./deploy');

  config = require('./config');

  cli = function() {
    var args, configCommand;
    commander.version(_p.version).usage('<command> [options] [projects]');
    commander.command('deploy').usage('[options] [projects]').description('deploy local projects to servers').option('-c, --config <config>', 'user defined configure file').option('-f, --force', 'force deploy repository').action(function() {
      var options, _options;
      options = _.last(arguments);
      _options = {
        projects: _.first(arguments, arguments.length - 1),
        force: options.force || false,
        config: options.config || null
      };
      return deploy(_options);
    });
    configCommand = commander.command('config');
    configCommand.command('show').description('show configure files');
    configCommand.command('add').description('add configure');
    configCommand.command('edit').description('edit configure');
    configCommand.description('add or update your configure file').option('-c, --config <config>', 'user defined configure file').action(function() {
      var action, options, _options;
      options = _.last(arguments);
      action = _.first(arguments);
      action = typeof action === 'string' ? action : null;
      _options = {
        action: action,
        configFile: options.config
      };
      return config(_options);
    });
    args = commander.parse(process.argv);
    if (process.argv.length < 3) {
      return commander.help();
    }
  };

  module.exports = cli;

}).call(this);
