// Generated by CoffeeScript 1.6.3
/*
sneaky clients
these clients need to be deployed on remote servers
*/


(function() {
  var Client, async, cpuMonitor, diskMonitor, memoryMonitor, _ref;

  async = require('async');

  _ref = require('./monitors'), cpuMonitor = _ref.cpuMonitor, memoryMonitor = _ref.memoryMonitor, diskMonitor = _ref.diskMonitor;

  Client = (function() {
    function Client() {}

    Client.prototype.publish = function() {};

    return Client;

  })();

  module.exports = Client;

}).call(this);
