// Generated by CoffeeScript 1.6.3
/*
sneaky clients
these clients need to be deployed on remote servers
*/


(function() {
  var Client, CpuMonitor, DiskMonitor, MemoryMonitor, async, e, i, monitors, name, _ref;

  CpuMonitor = require('./monitors/cpu');

  MemoryMonitor = require('./monitors/memory');

  DiskMonitor = require('./monitors/disk');

  try {
    _ref = ['cpu', 'memroy', 'disk'];
    for (i in _ref) {
      name = _ref[i];
      monitors = new require("./monitors/" + name);
    }
  } catch (_error) {
    e = _error;
  }

  async = require('async');

  Client = (function() {
    function Client() {
      this.cpuMonitor = new CpuMonitor();
      this.memoryMonitor = new MemoryMonitor();
      this.diskMonitor = new DiskMonitor();
    }

    Client.prototype.publish = function() {
      return async.eachSeries;
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
