// Generated by CoffeeScript 1.6.3
(function() {
  if (typeof task !== "undefined" && task !== null) {
    require('./task');
  }

  module.exports = {
    deploy: require('./deploy'),
    Client: require('./client'),
    Server: require('./server')
  };

}).call(this);
