// Generated by CoffeeScript 1.6.3
/*
monitor server
this server will provide a web interface for server data
*/


(function() {
  var server;

  server = function() {};

  module.exports = server;

}).call(this);
