// Generated by CoffeeScript 1.6.3
/*
monitor server
this server will provide a web interface for server data
*/


(function() {
  var CpuMonitor, Logger, Server, http, port;

  http = require('http');

  port = 3356;

  Logger = require('./logger');

  CpuMonitor = require('./monitors/cpu');

  Server = (function() {
    function Server() {
      this.logger = new Logger();
    }

    Server.prototype.serv = function() {
      var cpuMonitor,
        _this = this;
      this.server = http.createServer(function(req, res) {});
      this.server.listen(port);
      this.logger.log("server listen on " + port);
      cpuMonitor = new CpuMonitor;
      return cpuMonitor.monitor();
    };

    Server.serv = function() {
      var server;
      server = new Server();
      server.serv();
      return server;
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
