// Generated by CoffeeScript 1.6.3
/*
monitor server
this server will provide a web interface for server data
*/


(function() {
  var Router, Server, express, http, logger, port;

  express = require('express');

  http = require('http');

  port = 3356;

  logger = require('graceful-logger');

  Router = require('./Router');

  Server = (function() {
    function Server() {}

    Server.prototype.serv = function() {
      var _this = this;
      this.app = express();
      this.server = http.createServer(this.app);
      this.app.configure(function() {
        _this.app.use(express.cookieParser());
        _this.app.use(_this.app.router);
        _this.app.use(express.favicon("" + __dirname + "/../public/favicon.ico"));
        _this.app.use('/', express["static"]("" + __dirname + "/../public"));
        _this.app.get('/users/:id', function(req, res) {
          return Router.aliasRoute(req, res, {
            ctrl: 'user',
            method: 'index'
          });
        });
        return Router.route(_this.app);
      });
      this.server.listen(port);
      return logger.info("server listen on " + port);
    };

    Server.serv = function() {
      var server;
      server = new Server();
      server.serv();
      return server;
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
