// Generated by CoffeeScript 1.6.3
(function() {
  option('-c', '--config [config]', 'define the .sneakyrc file path, default is ~/.sneakyrc');

  task('deploy', 'deploy source code to your servers', function(options) {
    return require('./deploy')(options);
  });

}).call(this);
