// Generated by CoffeeScript 1.6.3
(function() {
  var BaseController, crypto;

  crypto = require('crypto');

  BaseController = (function() {
    function BaseController() {}

    BaseController._toHash = function(key, args, callback) {
      var _callback;
      _callback = function() {};
      if (typeof args[args.length - 1] === 'function') {
        _callback = args[args.length - 1];
        args[args.length - 1] = callback || function(err, result) {
          var hash, mixKey;
          mixKey = "" + key + (JSON.stringify(args));
          hash = crypto.createHash('sha1').update(JSON.stringify(result)).digest('hex');
          return _callback(err, hash);
        };
      }
      return this.apply(this, args);
    };

    return BaseController;

  })();

  module.exports = BaseController;

}).call(this);
