// Generated by CoffeeScript 1.6.3
(function() {
  var exportsAll;

  exportsAll = function(list, postfix) {
    var modules;
    modules = {};
    list.forEach(function(name) {
      var className;
      className = "" + (name[0].toUpperCase()) + name.slice(1) + postfix;
      modules[className] = require("./" + name);
      return modules["" + (className[0].toLowerCase()) + className.slice(1)] = new modules[className];
    });
    return modules;
  };

  module.exports = exportsAll(['user', 'base'], 'Controller');

}).call(this);
