// Generated by CoffeeScript 1.6.3
(function() {
  var CpuMonitor;

  CpuMonitor = (function() {
    function CpuMonitor() {}

    CpuMonitor.prototype.monitor = function(callback) {
      return callback(null, os.loadavg());
    };

    return CpuMonitor;

  })();

  module.exports = CpuMonitor;

}).call(this);
