// Generated by CoffeeScript 1.6.3
(function() {
  var DiskMonitor, exec;

  exec = require('child_process').exec;

  DiskMonitor = (function() {
    function DiskMonitor() {}

    DiskMonitor.prototype.monitor = function(callback) {
      return exec('df -k', callback);
    };

    return DiskMonitor;

  })();

  module.exports = DiskMonitor;

}).call(this);
