// Generated by CoffeeScript 1.6.3
(function() {
  var MemoryMonitor;

  MemoryMonitor = (function() {
    function MemoryMonitor() {}

    MemoryMonitor.prototype.monitor = function(callback) {
      return callback(null, {
        total: os.totalmem(),
        free: os.totalmem()
      });
    };

    return MemoryMonitor;

  })();

  module.exports = MemoryMonitor;

}).call(this);
