// Generated by CoffeeScript 1.6.3
(function() {
  var MongodbMonitor, exec;

  exec = require('child_process').exec;

  MongodbMonitor = (function() {
    function MongodbMonitor() {}

    MongodbMonitor.prototype.monitor = function(callback) {};

    return MongodbMonitor;

  })();

  module.exports = MongodbMonitor;

}).call(this);
