// Generated by CoffeeScript 1.6.3
(function() {
  var RedisMonitor, exec;

  exec = require('child_process').exec;

  RedisMonitor = (function() {
    function RedisMonitor() {}

    RedisMonitor.prototype.monitor = function(callback) {};

    return RedisMonitor;

  })();

  module.exports = RedisMonitor;

}).call(this);
