// Generated by CoffeeScript 1.8.0
(function() {
  var async, execCmd, parse;

  async = require('async');

  execCmd = require('../util').execCmd;

  parse = function(project, options, dest) {
    var cmd, destination, host, port, user;
    destination = dest.destination, user = dest.user, host = dest.host, port = dest.port;
    port || (port = 22);
    if ((user != null) && (host != null)) {
      cmd = "ssh -t -t " + user + "@" + host + " -p " + port + " \"" + project.after + "\"";
    } else {
      cmd = project.after;
    }
    return cmd;
  };

  module.exports = function(project, options, callback) {
    var _ref;
    if (callback == null) {
      callback = function() {};
    }
    if (typeof project.after !== 'string') {
      return callback();
    }
    if (!((_ref = project.destinations) != null ? _ref.length : void 0)) {
      return callback();
    }
    return async.eachSeries(project.destinations, function(dest, next) {
      var cmd;
      cmd = parse(project, options, dest);
      return execCmd(cmd, next);
    }, callback);
  };

}).call(this);
