// Generated by CoffeeScript 1.6.3
(function() {
  var async, execCmd, parse;

  async = require('async');

  execCmd = require('../util').execCmd;

  parse = function(project, options, i) {
    var cmd, dest, destination, port, server, _ref, _ref1;
    destination = project.destinations[i];
    if (destination.indexOf('@') === -1) {
      cmd = project.after;
    } else {
      _ref = destination.split(':'), server = _ref[0], dest = _ref[1];
      port = ((_ref1 = project.ports) != null ? _ref1[i] : void 0) || 22;
      cmd = "ssh -t -t " + server + " -p " + port + " \"" + project.after + "\"";
    }
    return cmd;
  };

  module.exports = function(project, options, callback) {
    var count, prefix, _ref;
    if (callback == null) {
      callback = function() {};
    }
    if (typeof project.after !== 'string') {
      return callback();
    }
    prefix = project.name + '/';
    count = (_ref = project.destinations) != null ? _ref.length : void 0;
    if (!count) {
      return callback();
    }
    return async.times(count, function(i, next) {
      var cmd;
      cmd = parse(project, options, i);
      return execCmd(cmd, next);
    }, callback);
  };

}).call(this);
