// Generated by CoffeeScript 1.7.1
(function() {
  var async, execCmd, path;

  async = require('async');

  path = require('path');

  execCmd = require('../util').execCmd;

  module.exports = function(project, options, callback) {
    var cmd, prefix, remote;
    if (callback == null) {
      callback = function() {};
    }
    prefix = project.name + '/';
    project.source || (project.source = process.cwd());
    if (project.source.match(/^(http|git|ssh)/)) {
      remote = path.join(options.chdir, '.repos-' + project.name);
      cmd = "rm -rf " + (path.join(options.chdir, prefix)) + " " + remote + "; \\\ngit clone " + project.source + " " + remote + "; \\\ngit archive " + (project.version || 'HEAD') + " --prefix=" + prefix + " \\\n--remote=" + remote + " --format=tar | tar -xf - -C " + options.chdir;
    } else {
      cmd = "rm -rf " + (path.join(options.chdir, prefix)) + "; \\\ngit archive " + (project.version || 'HEAD') + " --prefix=" + prefix + " \\\n--remote=" + project.source + " --format=tar | tar -xf - -C " + options.chdir;
    }
    return execCmd(cmd, callback);
  };

}).call(this);
