// Generated by CoffeeScript 1.6.3
(function() {
  var execCmd, path;

  path = require('path');

  execCmd = require('../util').execCmd;

  module.exports = function(project, options, callback) {
    var cmd, prefix;
    if (callback == null) {
      callback = function() {};
    }
    prefix = project.name + '/';
    project.source || (project.source = process.cwd());
    cmd = "rm -rf " + (path.join(options.chdir, prefix)) + "; \\\ngit archive " + (project.version || 'HEAD') + " --prefix=" + prefix + " \\\n--remote=" + project.source + " --format=tar | tar -xf - -C " + options.chdir;
    return execCmd(cmd, callback);
  };

}).call(this);
