// Generated by CoffeeScript 1.8.0
(function() {
  var async, execCmd, path;

  async = require('async');

  path = require('path');

  execCmd = require('../util').execCmd;

  module.exports = function(project, options, callback) {
    var cmd, prefix, remote;
    if (callback == null) {
      callback = function() {};
    }
    prefix = project.name + '/';
    project.source || (project.source = process.cwd());
    if (project.source.match(/^(http|git|ssh)/)) {
      project.nochdir = false;
      remote = path.join(options.chdir, '.repos-' + project.name);
      cmd = ["rm -rf " + (path.join(options.chdir, prefix)) + " " + remote + ";", "git clone " + project.source + " " + remote + ";", "git archive " + (project.version || 'HEAD') + " --prefix=" + prefix, "--remote=" + remote + " --format=tar | tar -xf - -C " + options.chdir].join(' ');
    } else {
      if (project.nochdir) {
        return callback();
      }
      cmd = ["rm -rf " + (path.join(options.chdir, prefix)) + ";", "git archive " + (project.version || 'HEAD') + " --prefix=" + prefix, "--remote=" + project.source + " --format=tar | tar -xf - -C " + options.chdir].join(' ');
    }
    return execCmd(cmd, callback);
  };

}).call(this);
