// Generated by CoffeeScript 1.7.1
(function() {
  var execCmd, logger;

  logger = require('graceful-logger');

  execCmd = require('../util').execCmd;

  module.exports = function(project, options, callback) {
    var prefix;
    if (callback == null) {
      callback = function() {};
    }
    if ((project.before != null) && typeof project.before === 'string') {
      prefix = project.name + '/';
      process.chdir("" + options.chdir + "/" + prefix);
      return execCmd(project.before, callback);
    } else {
      return callback(null);
    }
  };

}).call(this);
