// Generated by CoffeeScript 1.6.3
(function() {
  var async, execCmd, parse;

  async = require('async');

  execCmd = require('../util').execCmd;

  parse = function(project, options, i) {
    var cmd, destination, excludes, port, _ref, _ref1;
    destination = project.destinations[i];
    if ((_ref = project.excludes) != null ? _ref.length : void 0) {
      excludes = project.excludes.map(function(item) {
        return "--exclude=" + item;
      });
    } else {
      excludes = [];
    }
    port = ((_ref1 = project.ports) != null ? _ref1[i] : void 0) || 22;
    if (destination.indexOf('@') === -1) {
      cmd = "rsync -a --timeout=15 --delete-after --ignore-errors --force \\\n" + (excludes.join(' ')) + " \\\n" + options.chdir + "/" + project.name + "/ " + destination;
    } else {
      cmd = "rsync -a --timeout=15 --delete-after --ignore-errors --force \\\n-e \"ssh -p " + port + "\" " + (excludes.join(' ')) + " \\\n" + options.chdir + "/" + project.name + "/ " + destination;
    }
    return cmd;
  };

  module.exports = function(project, options, callback) {
    var count, _ref;
    if (callback == null) {
      callback = function() {};
    }
    count = (_ref = project.destinations) != null ? _ref.length : void 0;
    if (!count) {
      return callback(new Error("missing destinations in project: " + project.name));
    }
    return async.times(count, function(i, next) {
      var cmd;
      cmd = parse(project, options, i);
      return execCmd(cmd, next);
    }, callback);
  };

}).call(this);
