// Generated by CoffeeScript 1.8.0
(function() {
  var async, execCmd, parse, parser, path;

  path = require('path');

  async = require('async');

  execCmd = require('../util').execCmd;

  parser = {
    excludes: function(project) {
      var excludes, _ref;
      if (!((_ref = project.excludes) != null ? _ref.length : void 0)) {
        return '';
      }
      excludes = project.excludes.map(function(item) {
        return "--exclude=" + item;
      });
      return excludes.join(' ');
    },
    includes: function(project) {
      var includes, _ref;
      if (!((_ref = project.includes) != null ? _ref.length : void 0)) {
        return '';
      }
      includes = project.includes.map(function(item) {
        return "--include=" + item;
      });
      return includes.join(' ');
    }
  };

  parse = function(project, options, dest) {
    var cmd, destination, host, port, sourceDir, user, _ref;
    destination = dest.destination, user = dest.user, host = dest.host, port = dest.port;
    port || (port = 22);
    if ((_ref = project.only) != null ? _ref.length : void 0) {
      project.excludes = ['*'];
      project.includes = project.only;
    }
    if (project.nochdir) {
      sourceDir = process.cwd();
    } else {
      sourceDir = path.join(options.chdir, project.name);
    }
    if ((user != null) && (host != null)) {
      cmd = ["rsync -a --delete-after --ignore-errors --force", "-e \"ssh -p " + port + "\"", parser.includes(project), parser.excludes(project), "" + sourceDir + "/", "" + user + "@" + host + ":" + destination].join(' ');
    } else {
      cmd = ["rsync -a --timeout=15 --delete-after --ignore-errors --force", parser.includes(project), parser.excludes(project), "" + sourceDir + "/", destination].join(' ');
    }
    return cmd;
  };

  module.exports = function(project, options, callback) {
    var _ref;
    if (callback == null) {
      callback = function() {};
    }
    if (!((_ref = project.destinations) != null ? _ref.length : void 0)) {
      return callback(new Error("missing destinations in project: " + project.name));
    }
    return async.eachSeries(project.destinations, function(dest, next) {
      var cmd;
      cmd = parse(project, options, dest);
      return execCmd(cmd, next);
    }, callback);
  };

}).call(this);
